### ISSUE TITLE
Errant * Symbols

### ISSUE THREAD

**Issue by cwfitzgerald** [kennethgoodman/rockstar_math#1]
This is a byproduct of how rockstar-py works, but there is invalid code on line 104 because of the symbol `*` in the code. This isn't valid as https://rockstar.connorwfitzgerald.com/OgNLg8vpPJ4 shows. If you change it to use `times` it works fine: https://rockstar.connorwfitzgerald.com/Ss106eaz1AI

**Comment by kennethgoodman** [comment]
Thanks, will fix
