### ISSUE TITLE
Rewrite all loops to end when two successive iterations are close enough

### ISSUE THREAD

**Issue by DavideFauri** [kennethgoodman/rockstar_math#15]
Making use of the `is_close` function implemented in https://github.com/kennethgoodman/rockstar_math/pull/14, it would be nice to refactor all loops so that they stop iterating when they stabilize around the desired value. That is, when the Taylor series converges within a reasonable range of the limit value.

This means changing all the:
```while the iterator is less than N``` 
into (pseudocode):
```while Is Close taking the prevnumber, the currentnumber is false and the iterator is less than N```

If everything works as intended, this should speed up some computations while still having a hard limit on iterations for difficult edge cases that do not converge well.

**Comment by kennethgoodman** [comment]
Pr merged and fixes ussie
